def define(F, dg, ch, d2, strip):
    wealth_rows=[("Chase retail","everyday banking","CCB","Branches and app; mass market; scale economics"),
     ("Chase Private Client","$150,000+ (US)","CCB","Branch banker plus a J.P. Morgan advisor"),
     ("J.P. Morgan Private Client","$750,000+ (US, launched 2024)","CCB","First Republic-style dedicated banker and concierge service"),
     ("J.P. Morgan Wealth Management","broad; ~6,000 advisors","CCB","Advisors in branches, self-directed investing, Wealth Plan"),
     ("J.P. Morgan Private Bank","~$10m+ (US); ~£10m+ UK (indicative)","AWM","Team-based, global, lending and trust; ~4,100 advisors"),
     ("23 Wall","800+ families, avg net worth ~$5bn","AWM","Institutional-style coverage of the largest families")]
    F("master", d2.master(), "The master diagram. Read it once now and once after Part 12.", full=True)
    F("value_chain", d2.value_chain(), "The role's value chain from internal demand to outcome. The intern touches every step but owns none of them yet.")
    F("two_channels", d2.two_channels(), "The two channels through which an Advisor's work is done. Junior bankers live mostly in channel 1; senior bankers mostly in channel 2.")
    F("worked_day", d2.worked_day(), "A worked day in the seat, illustrative. Times are composite; the mix of client, prospect, internal and control work is the point.")
    F("team_model", strip(dg.team_model()), "The five seats around one client. The Advisor is the single point of accountability; the specialists are shared across a team's clients [S28][S13].")
    F("hub", d2.hub(), "Why a relationship role exists: the tangle without one owner, the wheel with one.")
    F("request_life", d2.request_life(), "The life of one request (a loan) through the function. The Advisor owns the client-facing ends and is accountable for the middle.")
    F("collision", d2.collision(), "The scarce-resource collision and how it is allocated. An intern's job in a collision is to surface it, not to settle it.")
    F("walls", d2.walls(), "The walls around the Advisor's work and what may cross each.")
    F("unit_anatomy", d2.unit_anatomy(), "Anatomy of one UK banker team and what it draws from the centre. Reconstructed; see the confidence notes on the figure.")
    F("wiring", d2.wiring(), "How a banker team is wired into the centre: embedded, connective and utility roles.")
    F("team_org", None, "Reconstructed UK Private Bank org chart, colour-coded by confidence (green: confirmed by the firm's pages or press; amber: reported by a single source; grey: inferred from postings).")
    F("hiring_map", None, "What the Private Bank is hiring for in EMEA: open postings by function and city at the time of research.")
    F("size_vs_staff", d2.size_vs_staff([("J.P. Morgan AWM",7.1,10.15),("Morgan Stanley Wealth",9.3,15.5),("UBS Global Wealth",4.8,9.5),("Bank of America GWIM",4.8,19.0),("Goldman AWM",3.6,1.2),("Coutts",0.08,0.5),("Julius Baer",0.6,1.4)]), "Size against staffing for the firm and peers. Advisor counts for Morgan Stanley, UBS and Bank of America are press estimates and include mass-affluent advisers; Goldman's is its private wealth adviser count. Estimates are marked on the chart. [S150]-[S161][S300][S316]")
    F("money_flow", d2.money_flow(), "Where the money comes from and where it goes, FY2025. Full page.", full=True)
    F("operating_layers", d2.operating_layers(), "The firm's operating model as layers: customers and capital, the front line, the centre, and what flows between them.")
    F("firm_org", strip(dg.firm_org()), "The four reportable segments since the 2024 reorganisation [S300]. The Global Private Bank sits inside AWM; Chase's own wealth offering sits inside CCB.")
    F("segment_split", ch.bars("FY2025 revenue and net income by segment ($bn, managed basis)",["Consumer & Community Banking","Commercial & Investment Bank","Asset & Wealth Management","Corporate"],[("Revenue",[76.0,78.5,24.1,7.0]),("Net income",[18.2,27.8,6.5,4.5])],fmt=lambda v:f"{v:.0f}",note="Source: FY2025 Form 10-K [S300]"), "The CIB is now the largest revenue and profit engine; AWM is small by revenue and highest in return on equity (40%) [S300].")
    F("growth", ch.bars("Growth of the firm: employees (000s), branches (000s) and Private Bank advisors (000s), 2021 to 2025",["2021","2022","2023","2024","2025"],[("Employees (000s)",[271,294,310,317,319]),("Branches (000s)",[4.8,4.8,4.9,5.0,5.1]),("PB advisors (000s)",[2.7,3.1,3.5,3.8,4.1])],fmt=lambda v:f"{v:g}",ymax=360,note="Sources: 10-Ks [S300][S301][S302][S303]; advisors 2021-22 derived",colors=("#2a78d6","#eb6834","#1baf7a")), "Growth of the firm over time. Employees are in thousands; branches and Private Bank advisors are also in thousands, so the small bars are read against their own labels. Advisors for 2021 and 2022 are derived from firmwide totals (estimate).")
    F("firm_trend", ch.bars("JPMorgan Chase managed revenue and net income, 2021 to 2025 ($bn)",["2021","2022","2023","2024","2025"],[("Revenue",[125.3,132.3,162.4,180.6,185.6]),("Net income",[48.3,37.7,49.6,58.5,57.0])],fmt=lambda v:f"{v:.0f}",note="2023 includes First Republic from May; 2024 includes a $7.9bn Visa gain [S300][S303]"), "Five years of revenue and profit [S300][S303].")
    F("centre_org", d2.centre_org(), "The AWM centre's leadership as the firm publishes it, with placeholders where no name was verified.")
    F("firm_leadership", ch.firm_leadership(), "Senior leadership as of September 2026, after the June 2026 co-president appointments [S326][S337].")
    F("timeline", None, "Six years in one line: firm, AWM and Private Bank events, deals and macro.")
    F("team_vs_alt", d2.team_vs_alternative(), "The integrated team model against the lone-banker or wirehouse-grid model, side by side.")
    F("flywheel", strip(dg.flywheel()), "Mary Erdoes' four 'ingredients for growth' from the 2021 letter, drawn as the loop they form [S312].")
    F("why_works", None, "Why the structure works: the share-of-wallet arithmetic the firm discloses.")
    F("boundaries", d2.boundaries(), "The boundary between the Private Bank and the rest of the firm: what is shared, what is never shared, and why.")
    F("one_firm", ch.one_firm(), "The referral engine around the Global Private Bank. Every arrow runs both ways; no internal pricing is applied [S320].")
    F("wealth_continuum", strip(dg.wealth_continuum(wealth_rows)), "The wealth ladder across CCB and AWM. Thresholds are indicative and vary by market [S219][S332][S38].")
    F("pb_revenue", strip(dg.pb_revenue()), "The four revenue legs of a private bank relationship [S300].")
    F("customer_view", d2.customer_view(), "The customer's view: the record against alternatives, in the firm's own disclosed measures.")
    F("stability", d2.stability_timeline(), "The stability timeline: client assets and flows, 2021 to 2025 [S312]-[S316].")
    F("jcurve", ch.jcurve(), "The advisor J-curve as Erdoes describes it [S317][S320].")
    F("awm_hierarchy", ch.awm_hierarchy(), "AWM and Global Private Bank leadership, September 2026 [S6][S10][S19][S22].")
    F("spectrum", None, "The competitive spectrum: design axes and where each rival sits.")
    F("rotce_compare", ch.hbars("Return on tangible common equity, FY2025 (%)",["Morgan Stanley","JPMorgan Chase","HSBC (ex-notables)","Goldman Sachs (approx.)","Wells Fargo (approx.)","Bank of America","UBS (underlying)","Barclays","Citigroup"],[21.6,20.0,17.2,15.5,15.0,14.2,13.7,11.3,7.7],unit="%",fmt=lambda v:f"{v:.1f}",highlight="JPMorgan Chase",note="Company reports [S150]-[S157][S300]; GS and Wells approximate (estimate)"), "Return on tangible common equity by bank, FY2025. Two figures are approximations from press and are labelled.")
    F("wealth_peers", ch.hbars("Client assets or invested assets, FY2025 ($tn)",["BlackRock (AUM)","Morgan Stanley Wealth","J.P. Morgan AWM","Bank of America GWIM","UBS Global Wealth","Goldman Sachs AWM","HSBC wealth balances","Citi Wealth balances"],[14.0,9.3,7.1,4.8,4.8,3.6,2.1,1.1],unit="tn",fmt=lambda v:f"${v:.1f}",highlight="J.P. Morgan AWM",note="Definitions differ [S150]-[S161][S175][S300]"), "Scale in wealth and asset management. Definitions differ by firm; directional only.")
    F("reg_timeline", None, "The regulation timeline for UK private banking, 1986 to 2027.")
    F("shift_map", None, "The industry shift map: the forces reshaping private banking and which way each pushes an Advisor.")
    F("funnel", d2.funnel(), "The selection funnel with the candidate's position marked.")
    F("protocol", d2.protocol(), "The four-step answer protocol with timing.")
    F("priority", d2.priority(), "The priority order for when good things collide in this role.")
    F("frame_tactics", d2.frame_tactics(), "Eight ways interviewers break a frame, and the counter to each.")
    F("ladder", None, "The scenario ladder: every JD duty, three rungs.")
    F("tree1", d2.decision_tree("Decision tree: a senior person asks you to skip a control","'Just open the account now; we'll get the documents next week.'",[("Is it a rule or a preference?","If a rule (KYC, suitability, approval): cannot skip.","Say so once, plainly, with the reason."),("Can I make it fast instead?","Offer the fastest compliant path: what do we need, who can get it today?","Do the legwork yourself."),("Do they push again?","Escalate to your team lead or compliance the same day; document.","Never silently comply; never silently refuse.")]), "Decision tree one: the control you are asked to skip.")
    F("tree2", d2.decision_tree("Decision tree: you hear something in a meeting that might be inside information","A client mentions their listed company is 'about to be bought'.",[("Is it public?","Check: if not announced, treat as material non-public information.","Do not act, trade, or repeat it."),("Who needs to know?","Tell compliance or your team lead immediately; record time and context.","Not colleagues, not friends, not the Investor."),("What about the client?","Do nothing on their accounts that could be linked to the information; let compliance direct.","Restrict; document; move on.")]), "Decision tree two: possible inside information.")
    F("why_firm", d2.why_firm_one_page(), "Why the firm, on one page: six mechanisms, each with a number and a source.", full=True)
    F("cheat", None, "The cheat sheet on one page.")
    F("emea", ch.emea_map_list(), "The Private Bank's EMEA footprint from the firm's locations pages [S8].")
