# Generates the question bank HTML fragment (inserted into Part 9) and Question_Bank.md
import os, re, html
B = os.path.dirname(os.path.abspath(__file__))

Q = [
("A. Motivation", [
 ("Why investor relations rather than an investing seat?",
  "Genuine interest in the client side; retention risk.",
  "What IR is to you (explaining, evidencing, serving) → a moment you enjoyed that kind of work → why it matters at a credit manager specifically.",
  "PSG sits on the ESG Deal Committee [S305]; DLF V was raised through five wrappers [S222]; Hayfin hired ex-consultants and allocators into PSG [S1].",
  "Calling IR a stepping stone to deals; not knowing the daily work (DDQs, RFPs, reporting)."),
 ("Why private credit?",
  "Understanding of why the asset class exists.",
  "Bank retreat → companies need lenders → investors want contractual floating-rate income → private credit fills the gap; one risk you take seriously.",
  "Flynn's founding thesis on bank capital rules [S105]; Europe 35.9% of 2025 private debt capital [S152].",
  "A generic 'fast-growing' answer; claiming it is low risk."),
 ("Why Hayfin?",
  "Firm-specific research expressed as mechanism.",
  "Use the 30-second answer in Part 12: one platform with several doors → why that matters to an LP → why PSG is where that is explained.",
  "8%+ and 15%+ lender [S307]; DLF V >€15bn [S71]; conflict rules [S305].",
  "Adjectives ('leading', 'prestigious'); size alone; anything transplantable to Ares or ICG."),
 ("Walk me through your CV.",
  "Concise story; link from past work to IR skills.",
  "90 seconds: who you are → two experiences, each with one output and one skill (accuracy, client materials, data) → why this role now.",
  "JD: 'proactive', 'research... summarise... present', Excel and PowerPoint.",
  "Over two minutes; describing what the team did, not what you did."),
 ("What did you do in your last internship that is relevant here?",
  "Transferable output.",
  "Situation → the thing you produced (deck, model, data pack) → how you checked it → what happened.",
  "Map to JD duties: pitch materials, data, proofreading.",
  "No concrete output; no error you caught."),
 ("Where do you see yourself in five years?",
  "Retention and realism.",
  "Building expertise in investor work → a product or coverage track → specific skill you want (e.g. structuring vehicles for insurers).",
  "Two PSG tracks: product strategy and coverage [S1]; Coriani's path from intern to MD [S288].",
  "'Running my own fund'; 'moving to the deal team'."),
]),
("B. Firm", [
 ("What do you know about Hayfin?",
  "Accuracy and currency of facts.",
  "Founded 2009 → strategies → size and DLF V → ownership → one thing that interests you.",
  "~€40bn AUM Q2 2026 [S224]; MBO completed Feb 2025 [S73]; Mubadala, AXA IM Prime, Samsung Life [S74][S75].",
  "Saying €30bn or ten offices (stale)."),
 ("What has Hayfin announced recently?",
  "News flow; round one in a 2025 IR process covered recent deals and news [S261].",
  "Pick three: one fund, one office or hire, one deal; give a 'so what' for each.",
  "DLF V [S71]; Seoul office [S223]; Condis €305m [S231]; Marsh hire [S226].",
  "Listing headlines without implication."),
 ("What does the Partner Solutions team do?",
  "Whether you read the JD and beyond.",
  "Raise → diligence → service → content; who it serves; where you would sit.",
  "Coverage co-heads, product strategy, regions [S1]; quarterly report contents [S305].",
  "Describing it as sales only; forgetting reporting and SMAs."),
 ("Which strategy would you pitch to a Korean insurer, and in what wrapper?",
  "Link between investor type and product.",
  "Investor's need (long-dated, capital-efficient, rated) → strategy (senior DL) → wrapper (rated note feeder or SMA) → one risk to disclose (currency).",
  "$600m rated feeder [S237]; ~€1bn for Korean clients [S239]; Samsung Life shareholder [S75].",
  "Ignoring regulatory capital and currency."),
 ("What did you think of our recent insight pieces?",
  "Depth of preparation.",
  "Name one, summarise in two sentences, add one question it raised for you.",
  "'What a €15bn Fundraise Tells Us' [S222]; 'A Tale of Three PIKs' [S229]; 'The Complexity Premium' [S262].",
  "Claiming to have read without being able to summarise."),
 ("What makes Hayfin's culture different?",
  "Values fit, using Hayfin's own words.",
  "One quote → one example from your life that matches it.",
  "'rewarded to collaborate, rather than outperform peers' [S305]; 'no superstar culture... midfield general' [S281]; five values in the JD pack.",
  "Generic 'collaborative and entrepreneurial'."),
 ("Who are our competitors and how are we different?",
  "Competitive awareness (a named 2026 intern task [S265]).",
  "Name three peers → one axis where Hayfin differs from each → where Hayfin does not lead.",
  "Ares ACE VI €17.1bn [S135]; ICG SDP 5 [S132]; Arcmont (Nuveen) [S131]; independence and breadth.",
  "Claiming Hayfin is the biggest or has the best returns."),
]),
("C. Industry and credit technicals", [
 ("What is direct lending, and how is it different from syndicated loans and high-yield bonds?",
  "Product basics.",
  "Who lends → how terms are set → whether it trades → rate type → protections.",
  "Floating, senior secured, bilateral or small club; 40% of Hayfin DL sole-lender [S95].",
  "Mixing fixed and floating; forgetting illiquidity."),
 ("Why would an investor choose private credit over high yield?",
  "Trade-offs.",
  "Extra spread for illiquidity and complexity → floating rate → covenants and control → but: illiquid, model marks, lock-up.",
  "PitchBook: the key metric is 'excess spread' over public fixed income [S151].",
  "Calling it lower risk outright."),
 ("What makes direct lending attractive now, and what are the risks?",
  "Balance.",
  "Two tailwinds, two risks, one view.",
  "Bank retreat [S221]; Europe in favour [S152]; PIK creep [S245]; deal volumes down 29% [S240].",
  "One-sided bull case."),
 ("Explain PIK. When is it good or bad?",
  "Nuance on the 2026 hot topic.",
  "Definition → planned PIK at entry vs PIK forced by stress → how an LP should see it.",
  "'Three PIKs': good, bad, fake good [S229]; Lincoln 'shadow default' 6.2% [S162].",
  "'PIK is always a red flag.'"),
 ("What is unitranche?",
  "Structure knowledge.",
  "One loan replacing senior plus junior → one price, one lender group → speed and certainty for the sponsor.",
  "Condis €305m sole-lender unitranche [S231].",
  "Confusing it with mezzanine."),
 ("Walk me through an LBO from the lender's side.",
  "Credit lens (asked in a 2025 IR process [S261]).",
  "Sponsor buys company with equity plus debt → lender sizes debt on EBITDA and cash flow → covenants → repaid from cash flow or refinancing.",
  "Leverage = debt / EBITDA; Portfolio Breakdown reports LTM EBITDA, EV, leverage [S305].",
  "Answering only from the equity side."),
 ("How do rate moves affect a floating-rate lender?",
  "Rate sensitivity both ways.",
  "Higher rates → more income → but weaker interest coverage for borrowers → more PIK and amendments; cuts do the reverse.",
  "PitchBook expects 'cooler returns' as rates fall [S152].",
  "Forgetting borrower stress."),
 ("What is a covenant, and what is covenant-lite?",
  "Lender protections.",
  "A promise (e.g. leverage below X) → early warning → seat at the table before default; cov-lite removes maintenance tests.",
  "Hayfin: Europe has 'tighter documentation' than the US [S95].",
  "Not linking covenants to workout capability."),
 ("Why do private credit default rates differ so much?",
  "Data literacy.",
  "Definitions: payment default vs PIK switches vs covenant breaches → numbers → what LPs now ask for.",
  "Proskauer 2.51% [S155]; Fitch 6.3% [S245]; Lincoln 6.2% shadow [S162].",
  "Quoting one number as 'the' default rate."),
]),
("D. Investor relations specifics", [
 ("What is a DDQ and what goes in it?",
  "Core intern task.",
  "Purpose → standard templates → main sections → how a team answers efficiently.",
  "ILPA DDQ 2.0: 20 topics incl. succession, credit facilities, valuation, ESG, DEI, cyber [S299]; AIMA credit modules [S48].",
  "Vague answer; not mentioning consistency and sign-off."),
 ("How is an RFP different from a DDQ?",
  "Process understanding.",
  "RFP = competitive search for a mandate with fixed questions and deadline; DDQ = diligence on a chosen manager; both reuse the library.",
  "eVestment and consultant databases [S55].",
  "Treating them as the same."),
 ("Gross vs net IRR: what is the difference and why does it matter?",
  "Fees and honesty in marketing.",
  "Gross before fees and carry → net after → subscription lines lift IRR → rules require net alongside gross.",
  "SEC Marketing Rule FAQ, 19 Mar 2025 [S53]; SOCF I 13.1% gross vs 8.1% net [S307].",
  "Forgetting fund leverage and subscription lines."),
 ("Explain IRR, MOIC, DPI and TVPI.",
  "Fund metrics fluency.",
  "Define each in one line → which is realised vs unrealised → which LPs watch in a slow-exit market (DPI).",
  "ILPA Performance Template shows IRR and TVPI with and without subscription lines [S45].",
  "Mixing realised and unrealised."),
 ("How do LPs choose managers?",
  "Allocator thinking.",
  "Strategy fit → team and track record → process and controls → alignment and terms → operations → consultant view.",
  "Intralinks: strategy 51%, sector knowledge 30%, co-invest 22%, fees 14% [S189].",
  "'Best returns' only."),
 ("Who are Hayfin's investors and how do their needs differ?",
  "Client segmentation.",
  "Pensions (liabilities, pacing) → insurers (capital, ratings) → SWFs (scale, co-invest) → consultants (process).",
  "Pension 51.1%, insurance 19.5%, SWF 12.1%; Australia 22.8% [S305].",
  "Forgetting insurers and SWFs."),
 ("What is an SMA and why would an investor want one?",
  "JD vocabulary.",
  "Single-investor vehicle → custom terms, control, fees, reporting → needs size.",
  "JD's 'Special Memorandum Accounts' means separately managed accounts [S25].",
  "Not knowing the term, or repeating the JD's error."),
 ("What role do investment consultants play?",
  "Gatekeeper awareness.",
  "Advise many pension funds → rate managers → RFPs and databases → one rating can unlock many commitments.",
  "DLF V consultant involvement highest ever [S222]; Bringardner ex-BlackRock consultant relations [S4].",
  "Ignoring them."),
 ("What goes into a quarterly LP report?",
  "Reporting basics.",
  "Portfolio summary and track record → company-level data → letter → capital account → audited accounts annually.",
  "Hayfin's list: Summary of Investments, Portfolio Breakdown, CEO Letter, audited financials within 90 days [S305].",
  "Forgetting fees and expenses, watchlist, ESG."),
 ("How would you use AI tools to make the team more efficient?",
  "JD skill, with judgement.",
  "One use case → guardrails (approved sources, no confidential data in public tools, human check) → how you would measure the gain.",
  "Chicago posting: AI 'used with careful attention to accuracy' [S19]; DDQ 40-60 hours [S190].",
  "AI drafting client documents unchecked."),
]),
("E. Market awareness", [
 ("Tell me about a recent private credit headline and what it means for LPs.",
  "Commercial awareness with implication.",
  "Fact → why it happened → what it means for an investor → link to Hayfin.",
  "Redemption wave [S184][S243]; Fitch 6.3% [S245]; SEC valuation statement [S250].",
  "No 'so what'."),
 ("Is private credit a bubble?",
  "Balance and composure.",
  "Use the Part 8 debate: claim, evidence, objection, what would change your mind.",
  "ECB [S177] vs Dimon [S157]; Coller barometer [S183].",
  "Either extreme."),
 ("Why are US and Asian investors buying European direct lending?",
  "Link to PSG's own thesis.",
  "Diversification → fragmentation premium → bank retreat → closed-end structures after 2026 gating.",
  "Over half of DLF V from EMEA; growth from US and APAC [S222]; Pla on diversification [S277].",
  "Not mentioning diversification or currency."),
 ("How are insurers changing private credit?",
  "Wrapper and capital awareness.",
  "Long liabilities → need for yield with capital efficiency → rated feeders, SMAs, ABF.",
  "$600m rated note feeder [S237]; Solvency II reporting in Finance [S333].",
  "No idea of capital treatment."),
 ("What is happening in fundraising across private markets?",
  "Market structure.",
  "More money, fewer funds, longer closes, concentration in experienced managers.",
  "Preqin: 80 funds, top 10 took 64%, 39 months [S153]; PitchBook 93% to fund 4+ [S152].",
  "Unsourced numbers."),
]),
("F. Behavioural and competency", [
 ("Tell me about a time you produced work that needed very high attention to detail.",
  "JD: 'see things others don't see'.",
  "STAR, with the specific error you caught and the check that caught it.",
  "Proofreading quarterly reports [S305].",
  "No concrete error."),
 ("Tell me about juggling several deadlines.",
  "Prioritisation.",
  "The deadlines → how you ranked them (client impact, hard dates, dependencies) → what you told people → result.",
  "Quarter-end reporting plus live DDQs.",
  "No logic for the order."),
 ("Tell me about a setback and how you persisted.",
  "Persistence, which Flynn names [S281].",
  "Setback → what you changed → second attempt → what you still do differently.",
  "'persistence is an undervalued but incredibly important trait' [S281].",
  "A trivial example."),
 ("Tell me about making a team better rather than shining alone.",
  "'Midfield general' [S281].",
  "A team result → your enabling role (organising, checking, unblocking) → credit to others.",
  "'rewarded to collaborate, rather than outperform peers' [S305].",
  "A hero story."),
 ("Tell me about explaining something complex to a non-expert.",
  "Client communication; 'gravitas'.",
  "The concept → your analogy or picture → how you checked understanding.",
  "Explaining PIK or gross vs net to a trustee board.",
  "Jargon."),
 ("Tell me about a mistake you made.",
  "Honesty; Hayfin values say 'We do not hide our mistakes'.",
  "Own it in one sentence → fix → what you changed so it cannot recur.",
  "Value 'Excellence' in the JD pack.",
  "A fake weakness."),
]),
("G. Case and written exercises", [
 ("Here is fund performance data in Excel: calculate returns and comment.",
  "Excel speed, accuracy, commentary (reported 2025 IR case [S261]).",
  "Check data → compute IRR (XIRR), MOIC, DPI, TVPI → one chart → three bullet 'so whats' → caveats.",
  "Gross vs net; subscription line effect; currency.",
  "Formatting errors; no conclusion."),
 ("Pitch this fund to a UK pension fund in five minutes.",
  "Structure, investor-first framing.",
  "Their need → the strategy → why this manager (evidence) → risks and how managed → terms and next step.",
  "Pension 51% of Hayfin AUM [S305]; downside, PIK, loss-rate questions [S222].",
  "Listing features without linking to the pension's liabilities."),
 ("Draft a DDQ answer: describe your valuation policy.",
  "Precision and tone.",
  "Who values, how often, independent input, committee, escalation; mark what you would confirm with Finance and Compliance.",
  "Valuation Committee; Finance reviews NAV before investors [S333]; FCA review good practice [S166].",
  "Overclaiming; inventing facts."),
 ("Write a one-page case study from this deal summary.",
  "JD task with compliance instincts.",
  "Situation → why Hayfin won → structure and protections → outcome → selection basis and disclaimers.",
  "COBS 4.2 [S49]; SEC FAQ [S53]; anti-greenwashing [S52].",
  "Disclosing confidential terms; no selection basis."),
 ("Group exercise: assess this borrower as a credit opportunity.",
  "Teamwork and credit basics (2024 dental case [S260]).",
  "Agree a structure and timekeeper → business quality → cash flow and leverage → downside and recovery → decision.",
  "Leverage, interest cover, covenants, sponsor support.",
  "Dominating; ignoring downside."),
]),
]

def html_out():
    out = []
    n = 0
    for cat, items in Q:
        out.append(f'<h3>{cat}</h3>')
        for q, t, s, f, tr in items:
            n += 1
            out.append(f'<div class="qa"><div class="q">{n}. {html.escape(q)}</div>'
                       f'<div><b>Tested:</b> {html.escape(t)} <b>Structure:</b> {html.escape(s)}</div>'
                       f'<div><b>Facts to weave in:</b> {html.escape(f)} <b style="color:#b3261e">Trap:</b> {html.escape(tr)}</div></div>')
    return '\n'.join(out), n

def md_out(n):
    L = ['# Hayfin Partner Solutions Group: Question Bank', '',
         f'{n} likely questions for the Summer 2027 PSG internship. Scaffolds, not scripts. [Sxx] markers refer to the source table in the main pack (Part 15). Built 8 October 2026.', '']
    k = 0
    for cat, items in Q:
        L += [f'## {cat}', '']
        for q, t, s, f, tr in items:
            k += 1
            L += [f'### {k}. {q}', f'- **Tested:** {t}', f'- **Structure:** {s}', f'- **Facts to weave in:** {f}', f'- **Trap:** {tr}', '']
    L += ['## Questions to ask them', '', 'See Part 9 of the pack for the full list with the research behind each one.', '']
    return '\n'.join(L)

if __name__ == '__main__':
    h, n = html_out()
    p = os.path.join(B, 'parts', '10_part9a.html')
    s = open(p).read()
    s = re.sub(r'<!--QBANK-->.*?<!--/QBANK-->|<!--QBANK-->', '<!--QBANK-->' + h + '<!--/QBANK-->', s, flags=re.S)
    open(p, 'w').write(s)
    open(os.path.join(B, 'Question_Bank.md'), 'w').write(md_out(n))
    print('questions', n)
