# Generates scenario cards for Part 11 (three per JD bullet)
import os, html, re
B = os.path.dirname(os.path.abspath(__file__))

# (bullet label, [ (level, title, setup, trap, say, why, twist) x3 ])
S = [
("R1 · Pitch materials, DDQ responses, investor presentations", [
 ("easy","Stale number","You notice the pitch book shows last quarter's AUM, and the coverage MD is sending it this afternoon.","Fixing it silently, or saying nothing to avoid looking pushy.","\"I've spotted the AUM on page 3 is Q1's; the Q2 figure is X from the investor report. Shall I update it and flag the change in the version log before it goes?\"","Accuracy and consistency across documents is the product; one wrong number in a deck an LP compares with a DDQ costs trust [S20][S59].","\"There's no time, just send it.\" Hold: \"Understood. It's a two-minute fix; can I make it and send you the updated PDF in five minutes?\""),
 ("med","DDQ answer you cannot source","A DDQ asks for DLF V's loss rate since inception. The library answer is from 2023 and you cannot find a newer approved figure.","Inventing or extrapolating a number to finish on time.","\"I've drafted everything except Q42 on loss rates. The approved figure is from 2023. Who should confirm the current number: Portfolio Management or Finance?\"","Hayfin says its \"track record and our loss rate are used by our investors to assess our success\" [S305]; an unapproved figure is a regulatory and reputational risk [S49].","\"Just use the old one with today's date.\" Hold: \"I'd rather mark it 'as of 2023, update to follow' than put a wrong date on it. That keeps us accurate and still meets the deadline.\""),
 ("hard","Two decks, two stories","Preparing an investor presentation, you find the software exposure figure differs between the pitch book (under 6%) and a draft case study (8%).","Picking the better number.","\"These two figures disagree. They may use different bases, for example the whole DL book versus one fund. Before either goes out, can we confirm the definition and source with the deal team?\"","Hayfin publishes \"less than 6%\" for the DL book and under 5% for the latest vintage [S227]; definitions matter as much as numbers.","\"The investor won't notice.\" Hold: \"They might compare it with the DDQ, and the consultant certainly will. It's quicker to fix now than to explain later.\""),
]),
("R2 · Ad hoc client requests", [
 ("easy","Urgent request on a Friday","An Australian SMA client asks at 4pm Friday for UK exposure by sector, needed Monday.","Promising a time you cannot meet, or waiting until Monday to acknowledge.","\"I'll acknowledge today, confirm exactly what they need (which date, which measure), build it from the portfolio file, and get a senior check on Monday morning.\"","Fast acknowledgement plus checked output is how IR is judged [S20]; Australia is 22.8% of AUM [S305].","\"Can you just send it tonight unchecked?\" Hold: \"I can have it ready tonight and reviewed first thing Monday, before their deadline.\""),
 ("med","Request that needs another investor's data","A pension asks how its terms compare with other LPs in the fund.","Sharing or hinting at another investor's terms.","\"I can't share other investors' terms. I'll ask the coverage MD how we usually answer this, for example by pointing to the MFN process in their side letter.\"","Investor confidentiality is a wall around PSG (Figure 1.5) [Inferred]; fair treatment of every LP comes before speed.","\"They're our biggest client.\" Hold: \"That's exactly why we should answer it the same way we would for anyone.\""),
 ("hard","A request that looks like it wants inside information","A hedge fund that is also an LP asks for the latest numbers on a named borrower whose bonds trade publicly.","Sending borrower data because they are an LP.","\"Borrower information may be confidential or non-public, and this investor may trade the bonds. I'd pass this straight to Compliance before replying.\"","MNPI rules apply [S301]; Hayfin runs public high-yield as well as private credit [S305].","\"It's in the quarterly report anyway.\" Hold: \"Then Compliance will clear it quickly. I'd still rather they decide.\""),
]),
("R3 · Case studies", [
 ("easy","Only winners","You are asked to pick three case studies for a pitch. The best returns are all realised deals in one sector.","Choosing the three best performers.","\"I'd propose a selection basis first, for example size, recency and a mix of sectors and outcomes, and note it in the footnote.\"","Cherry-picking misleads; COBS 4.2 fair, clear and not misleading [S49]; SEC rules require context for extracted performance [S53].","\"Marketing wants the best ones.\" Hold: \"We can still lead with strong deals; the basis just protects us if a consultant asks.\""),
 ("med","Gross only","A draft case study shows only gross IRR because net is not available at deal level.","Leaving it as is because everyone does it.","\"For US-facing material, gross for one deal needs the whole portfolio's gross and net shown with at least equal prominence. Should I add the fund-level figures and the standard disclaimer?\"","SEC Marketing Rule FAQ, 19 March 2025 [S53]; Hayfin's PES update already uses Rule 206(4)-1 language [S330].","\"This one is only for Europe.\" Hold: \"Then COBS 4.6 best practice still asks for the effect of fees. Compliance can tell us which version applies.\""),
 ("hard","An ESG claim you cannot evidence","A case study calls a borrower 'net zero aligned'; the ESG team has no data to support it.","Keeping the phrase because it reads well.","\"I'd change it to what we can evidence, or remove it, and check with the ESG team. The anti-greenwashing rule needs the claim to match the facts.\"","FCA ESG 4.3.1R [S52]; Hayfin trained PSG on it in 2024 [S25].","\"The sponsor said so.\" Hold: \"Then we can quote the sponsor's statement with attribution, if Compliance is happy.\""),
]),
("R4 · Quarterly LP reporting and proofreading", [
 ("easy","A total that does not add","Proofreading the Portfolio Breakdown, the sector percentages sum to 101.3%.","Assuming it is rounding and moving on.","\"Probably rounding, but 1.3 points is more than rounding usually explains. I'll check the source data and either fix it or add a rounding note.\"","Reports carry a \"line-by-line track record\" [S305]; consultants check totals.","\"It's always been like that.\" Hold: \"Then it's worth one check; if it's rounding, a footnote fixes it for good.\""),
 ("med","Late data from a deal team","Quarter-end. One deal team has not sent its company commentary and the report is due tomorrow.","Writing commentary yourself from old notes.","\"I'll chase with a specific ask and deadline, offer a draft from last quarter's text for them to edit, and tell my manager the risk now, not tomorrow.\"","IR and investment teams produce the reports jointly [S305]; escalate early, not late.","\"Just write something.\" Hold: \"I can draft it, but it has to be approved by the deal team before it goes out.\""),
 ("hard","An error found after sending","After the quarterly report goes out you find a borrower's leverage was misstated.","Hoping nobody notices.","\"I'd tell my manager straight away with the correct figure and the source, so we can decide how to correct it with investors.\"","Hayfin's values: \"We do not hide our mistakes\" (JD pack); correction is part of trust.","\"It's immaterial.\" Hold: \"That may be right; I'd still like the person who decides materiality to see it.\""),
]),
("S1 · Research across topics, summarise, present", [
 ("easy","Open research brief","A coverage MD asks: 'What are Korean insurers allocating to private credit?'","Delivering a 20-page dump.","\"I'll come back with one page: the headline answer, three facts with sources, what it means for us, and what I could not find.\"","PSG values short, sourced notes [S19]; Seoul office context [S223].","\"Can you also add Japan?\" Hold: \"Yes; I'll do Korea first by tomorrow and Japan by Thursday unless you'd rather swap.\""),
 ("med","Conflicting sources","Two reputable sources give different market sizes for European private credit.","Picking one silently.","\"I'd show both, explain the definitions behind each, and say which I'd use and why.\"","Definitions drive size (Figure 5.2) [S150][S182].","\"Just give me one number.\" Hold: \"Then I'd use X because it matches how we define our market, with a footnote.\""),
 ("hard","Presenting to someone senior who disagrees","You present your findings and a senior person says your conclusion is wrong.","Collapsing, or arguing.","\"That's useful. Which part do you see differently? If it's the data, I'll recheck it; if it's the interpretation, here's my reasoning, and I'd like to understand yours.\"","Frame-holding: separate facts from judgement (Part 11 method).","\"You clearly haven't understood the market.\" Hold: steady voice, \"That may be right. What would you look at first?\""),
]),
("S2 · Career in IR; discuss fundraising knowledgeably", [
 ("easy","Why not investing?","\"Wouldn't you rather be on the deal team?\"","Admitting IR is plan B.","\"I like the investing side, which is why I want to explain it well. What draws me to PSG is turning deal evidence into something an investor can underwrite.\"","PSG sits inside the deal approval workflow [S305].","\"Most interns say that.\" Hold: give your one concrete example of enjoying explanation work."),
 ("med","Explain fundraising","\"How does a fundraise actually work?\"","Vague talk about 'networking'.","\"Pre-marketing, then a first close, then subsequent closes to a final close; LPs go through consultant screens, RFPs, DDQs, IC and legal; the manager offers different wrappers for different investors.\"","Allocation process (Figure 6.1); DLF V wrappers [S222].","\"What's a first close for?\" Hold: \"It lets the fund start investing and creates momentum; later investors often pay the same fees.\""),
 ("hard","Knowledge trap","\"What's the hard cap on DLF V?\"","Guessing.","\"I haven't seen a hard cap published. The release says in excess of €15bn including related vehicles, and 9fin reported a €10bn target.\"","[S71][S238]; honesty beats a guess.","\"Surely you know that.\" Hold: \"I'd rather not guess a number you'd then repeat to an investor.\""),
]),
("S3 · AI tools; Excel and PowerPoint", [
 ("easy","AI idea","\"How would you use AI here?\"","Grand claims about automation.","\"A first-draft DDQ answer drawn only from the approved library, with every fact checked by a person and no confidential data in public tools.\"","Chicago posting: AI used \"with careful attention to accuracy\" [S19].","\"Isn't that slower?\" Hold: \"The draft saves time; the check protects us. The net is still faster.\""),
 ("med","AI got it wrong","An AI tool drafts an answer that cites a fund size that does not exist.","Trusting the tool because it sounds right.","\"I'd discard the number, find the source figure, and note the failure so the team knows where the tool is weak.\"","Accuracy rules (COBS 4.2) [S49].","\"Everyone uses it.\" Hold: \"I'll keep using it; I just won't ship anything I haven't checked.\""),
 ("hard","Excel under pressure","Live case: compute IRR and TVPI from a cash flow table in 20 minutes.","Formatting before checking signs and dates.","\"I'd set up dates and signed cash flows first, use XIRR, then MOIC, DPI and TVPI, sanity-check against a rough estimate, and only then chart.\"","Reported 2025 IR case [S261].","\"Your IRR looks high.\" Hold: \"Let me check whether a subscription line or a sign error is driving it.\""),
]),
("S4 · Fluent English, written and spoken", [
 ("easy","Rewrite for an LP","Rewrite a jargon-heavy paragraph for a pension trustee.","Adding more jargon to sound expert.","\"Short sentences, one idea each, define PIK in plain words, and end with what it means for them.\"","Writing standard of this pack; LP audience [S305].","\"Too simple?\" Hold: \"Trustees decide; clarity helps them decide.\""),
 ("med","Email tone","A consultant emails angrily about a late data template.","Being defensive.","\"Acknowledge, apologise for the delay without excuses, give a firm time, and deliver early.\"","Consultants matter more than ever [S222].","\"It wasn't our fault.\" Hold: \"Possibly; the fix is the same either way.\""),
 ("hard","Explain a loss","Explain to an LP in two minutes why a loan was restructured.","Hiding behind jargon.","\"What happened, what we did, where the investor stands now, and what we learned.\"","Workout capability is what LPs buy [S281].","\"So you lost money?\" Hold: \"On this loan, the recovery is X so far; across the portfolio, here's the context.\""),
]),
("A1 · Passion for markets and private capital", [
 ("easy","Why does private capital matter?","\"What role does private credit play in the economy?\"","A purely financial answer.","\"It lends to mid-sized companies banks now find costly to hold, which funds growth and jobs; Hayfin says over €59bn invested across 600+ companies since 2009.\"","[S79]; bank retreat [S105].","\"Isn't it just shadow banking?\" Hold: \"It is non-bank lending, with locked-up money rather than deposits; the risk is opacity, which is why reporting matters.\""),
 ("med","How do investors allocate?","\"Why would a pension commit to a seven-year illiquid fund?\"","Saying 'for returns'.","\"Its liabilities are long, it can accept illiquidity, and it gets floating-rate contractual income with covenants, above public credit.\"","Pension 51% of Hayfin AUM [S305]; excess spread [S151].","\"And if rates fall?\" Hold: \"Income falls too, but so does borrower stress.\""),
 ("hard","Contrarian push","\"I think private credit will blow up within two years. Convince me otherwise.\"","Either caving or fighting.","\"I wouldn't fully disagree: defaults are rising on broad measures. But cash defaults in senior loans are about 2.5%, and the ECB sees it as not systemic. The risk is dispersion, so manager choice matters.\"","[S245][S155][S177].","\"So you admit it's risky.\" Hold: \"Yes. Credit is always about pricing risk, not avoiding it.\""),
]),
("A2 · Organisation, priorities, deadlines", [
 ("easy","Three asks, one afternoon","Three people ask you for work due by 5pm.","Doing them in order received.","\"I'd list them with deadlines and client impact, tell each person when they'll get it, and ask my manager to rank if two truly clash.\"","Priority order (Figure 11.2).","\"Mine is most urgent.\" Hold: \"Then let's confirm with [manager] so the others know.\""),
 ("med","Quarter-end crunch","Reporting deadline and a live DDQ in the same week.","Quietly working all night and missing one.","\"Flag the clash early, propose a plan, and protect the external deadline that cannot move.\"","Audited accounts within 90 days; DDQ deadlines are external [S305].","\"Can't you do both?\" Hold: \"Yes, if X can review the DDQ on Thursday rather than Wednesday.\""),
 ("hard","Two senior people, one intern","Two MDs both say their request is top priority.","Choosing the more senior person.","Use the composure decision tree (Figure 11.5).","Fair service to every internal client.","\"Just do mine.\" Hold: \"Happy to; can I let [the other MD] know so they aren't left waiting?\""),
]),
("A3 · Attention to detail; complete all tasks", [
 ("easy","Typo in a borrower name","A borrower name is misspelt in a report going out tomorrow.","Thinking it's too small to mention.","\"Fix, log, and check the same name elsewhere in the pack.\"","\"see things others don't see\" (JD).","\"Nobody reads that page.\" Hold: \"The borrower's sponsor might.\""),
 ("med","Loose ends at internship end","Your last week; two tasks are 80% done.","Leaving them undocumented.","\"A handover note: status, files, sources, next steps, and who now owns each.\"","\"able to complete all tasks\" (JD).","\"Don't worry about it.\" Hold: \"It'll take me 20 minutes and saves someone two hours.\""),
 ("hard","Detail versus deadline","Perfecting a deck will miss the deadline by an hour.","Missing the deadline for cosmetic polish.","\"Send an accurate version on time; list the cosmetic fixes for the next version.\"","Priority: accuracy over polish, deadline over cosmetics.","\"It has to be perfect.\" Hold: \"Numbers will be perfect; fonts can follow.\""),
]),
("A4 · Explore the problem, innovate, present", [
 ("easy","Improve a process","\"What would you change about how we answer DDQs?\"","Criticising without knowing the process.","\"I'd first learn how the library works, then propose tagging answers by date and owner so stale ones flag themselves.\"","DDQ burden [S190].","\"We tried that.\" Hold: \"What stopped it? That's what I'd want to fix.\""),
 ("med","Case-study library","Pitch an idea in two minutes.","Vague 'use AI more'.","\"A case-study library linked to source data and pre-approved disclaimers, so every case study and DDQ answer pulls from one checked record.\"","Part 12 close; Marketing Rule disclaimers [S330].","\"Who maintains it?\" Hold: \"Product Strategy owns it; deal teams confirm facts quarterly.\""),
 ("hard","Idea rejected","Your idea is rejected in a team meeting.","Sulking or pushing harder.","\"Thank them, ask what would make it worth trying, and offer a small test.\"","Hayfin values: healthy debate, humbleness (JD pack).","\"It's a waste of time.\" Hold: \"Understood. Could I try it on one DDQ to see?\""),
]),
("A5 · Articulate; presenting with gravitas", [
 ("easy","Five-minute fund pitch","Pitch DLF V to a UK pension.","Starting with Hayfin's history.","\"Start with their need, then the strategy, the evidence, the risks, and the next step.\"","Part 9 case scaffold.","\"Why not just tell me returns?\" Hold: \"Net returns depend on the vintage; here's what drives them.\""),
 ("med","Interrupted mid-pitch","An interviewer cuts in: 'Skip that, what's the catch?'","Losing the thread.","\"The main risks are illiquidity, PIK creep in stressed borrowers, and currency for non-euro investors. Here's how each is managed.\"","Frame method: answer, then return.","\"That's it?\" Hold: \"Those are the three I'd put first; happy to go deeper on any.\""),
 ("hard","Silence after your answer","You finish; the interviewer says nothing for five seconds.","Filling the silence by undermining your answer.","Wait two seconds, then: \"Would it help if I went deeper on any part of that?\"","Counter to the 'silence' tactic (Figure 11.3).","Still silence. Hold: smile, wait; they will move on."),
]),
("A6 · Other languages (desirable)", [
 ("easy","Language link","\"You speak Korean; how would that help?\"","Overclaiming business fluency.","\"Reading local press and LP disclosures, and helping the Seoul team with materials, while professional translation handles anything formal.\"","Seoul office 1 Oct 2026 [S223].","\"Could you translate a DDQ?\" Hold: \"A first draft, yes; a formal one should be checked by a professional.\""),
 ("med","No extra language","\"You only speak English?\"","Apologising.","\"Yes; I'd bring curiosity about each market's investors, and I'm happy to learn the vocabulary of the region I support.\"","Desirable, not mandatory (JD).","\"Others do speak three.\" Hold: \"Then I'll compete on accuracy and research.\""),
 ("hard","Cultural mistake risk","A Middle East LP visit; you draft the agenda.","Ignoring local norms and calendars.","\"Ask the regional MD for norms, check dates against local holidays, and keep materials simple.\"","Coriani covers MENA [S288]; 10% of DLF V from the Middle East [S222].","\"We're in a rush.\" Hold: \"A two-minute check now avoids a bad first impression.\""),
]),
]

def gen():
    out = []
    lv = {"easy":"Easy","med":"Medium","hard":"Hard"}
    n = 0
    for label, cards in S:
        out.append(f'<h3>{html.escape(label)}</h3><div class="grid3">')
        for (l, t, setup, trap, say, why, twist) in cards:
            n += 1
            out.append(f'<div class="card {l}" style="margin:0"><div class="hd"><span>{html.escape(t)}</span><span>{lv[l]}</span></div><div class="bd">'
                       f'<p><b>Setup:</b> {html.escape(setup)}</p><p><b>Trap:</b> {html.escape(trap)}</p><p><b>Say:</b> {html.escape(say)}</p>'
                       f'<p><b>Why it works:</b> {html.escape(why)}</p><p><b>Twist:</b> {html.escape(twist)}</p></div></div>')
        out.append('</div>')
    return '\n'.join(out), n

if __name__ == '__main__':
    h, n = gen()
    p = os.path.join(B, 'parts', '12_part11.html')
    s = open(p).read()
    s = re.sub(r'<!--CARDS-->.*?<!--/CARDS-->|<!--CARDS-->', '<!--CARDS-->' + h + '<!--/CARDS-->', s, flags=re.S)
    open(p, 'w').write(s)
    print('cards', n)
